
```{r}
library(moin)


testdata <- sf::st_read("../vignettes/data/OldenburgerGraben/Placenames.shp") 

# MDM - Maximum Distance Modell
mdm <- modelgraph(testdata,
                  "mdm",
                  4000)

spatgraph_transform(x=mdm,output="tidygraph")

plot(spatgraph_transform(x=mdm,output="tidygraph"),
     vertex.size=10,
     vertex.label.cex=0.5,
     layout=sf::st_coordinates(testdata))






# PPA - Proximal Point Analysis
ppa <- modelgraph(testdata,
                  "ppa",
                  4)

spatgraph_transform(x=ppa,output="tidygraph")

plot(spatgraph_transform(x=ppa,output="tidygraph"),
     vertex.size=10,
     vertex.label.cex=0.5,
     layout=sf::st_coordinates(testdata))



############

dista <- sf::st_distance(x = testdata, 
                         y = testdata)

dista2 <- as.dist(dista)

clustertree <- hclust(dista2, method = "single")
plot(clustertree, hang = -1) 

memb <- cutree(clustertree, h = 1500)

testdata$Membership <- memb



```

```{r}
#mapview::mapview(testdata["Membership"])
plot(testdata["Membership"])
```

